name: timeagokk
description: a widget provided to the flutter scroll component drop-down refresh and pull up load.
version: 1.6.4
homepage: https://github.com/modoo-developer1/timeago.dart.git

environment:
  sdk: '>=2.12.0 <3.0.0'
  

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
